// Class automatically generated by Dev-C++ New Class wizard

#ifndef PRZEJSCIE_H
#define PRZEJSCIE_H

class Przejscie;

#include "controller.h"
#include <string>
using namespace std;
typedef unsigned char uchar;

/*
 * No description
 */
class Przejscie
{
	public:
	Przejscie();
	virtual ~Przejscie();
	string getName();
	void generate(Controller *C);
	
	protected:
	virtual uchar* generateFrame(float percent, int W, int H, uchar *Start, uchar *Stop)=0;
	
	string Name;
};

#endif // PRZEJSCIE_H
