// Class automatically generated by Dev-C++ New Class wizard

#include "PHsv.h" // class's header file
#include <cstdlib>

// class constructor
PHsv::PHsv()
{
	Name = "Zamiana HSV";
}

// class destructor
PHsv::~PHsv()
{
	// insert your code here
}

uchar* PHsv::generateFrame(float percent, int W, int H, uchar *Start, uchar *Stop)
{
    uchar* res = (uchar*) malloc(3*W*H);
    float p;
    wxImage::RGBValue rgb;
    wxImage::HSVValue hsv;
    for (int i=0; i<3*W*H; i+=3)
    {
        wxImage::RGBValue rgb1(Start[i], Start[i+1], Start[i+2]);
        wxImage::HSVValue hsv1 = wxImage::RGBtoHSV(rgb1);
        wxImage::RGBValue rgb2(Stop[i], Stop[i+1], Stop[i+2]);
        wxImage::HSVValue hsv2 = wxImage::RGBtoHSV(rgb2);
        if (percent<0.5)
        {
            p=2*percent;
            if (p<0.5)
            {
                hsv1.saturation*=1.0-p*2;
            }
            else
            {
                hsv1.saturation = hsv2.saturation*(2.0*(p-0.5));
                hsv1.hue = hsv2.hue;
            }
            //hsv1.hue = hsv1.hue*(1-p) + hsv2.hue*p;
            //hsv1.saturation = hsv1.saturation*(1-p) + hsv2.saturation*p;
        }
        else
        {
            p=(percent-0.5)*2.0;
            
            hsv1.hue = hsv2.hue;
            hsv1.saturation = hsv2.saturation;
            hsv1.value = hsv1.value*(1.0-p) + hsv2.value*p;
        }
        rgb1 = wxImage::HSVtoRGB(hsv1);
        res[i] = rgb1.red;
        res[i+1] = rgb1.green;
        res[i+2] = rgb1.blue;
    }
    return res;
}
