// Class automatically generated by Dev-C++ New Class wizard

#include "POdswiezanie_up.h" // class's header file
#include <cstdlib>

// class constructor
POdswiezanie_up::POdswiezanie_up()
{
	Name = "Odœwie¿anie od góry";
}

// class destructor
POdswiezanie_up::~POdswiezanie_up()
{
	// insert your code here
}

uchar* POdswiezanie_up::generateFrame(float percent, int W, int H, uchar *Start, uchar *Stop)
{

    
    uchar* res = (uchar*) malloc(3*W*H);
    int L=percent*H;
    for (int i=0; i<L; i++)
    {
        for (int j=0; j<3*W; j++)
        {
            res[i*3*W+j] = Stop[i*3*W+j];  
        }
    }
    
    for (int i=L; i<H; i++)
    {
        for (int j=0; j<3*W; j++)
        {
            res[i*3*W+j] = Start[i*3*W+j];  
        }
    }  

    return res;
}
